name: eFlows4HPC Pillar II ESM

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Pillar_II/esm/'
  push:
    paths:
      - 'Pillar_II/esm/'

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5
    steps:
      - name: Apt-Get Install
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Shellchecker
        run: |
          cd Pillar_II/esm/
          find . -name "*.sh" -exec shellcheck --external-sources {} \;

      - name: Install
        run: |
          cd Pillar_II/esm/
          pip install -r requirements.txt

      - name: MyPy
        run: |
          cd Pillar_II/esm/
          mypy src

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.10' ]

    env:
      TZ: ${{ matrix.time-zone }}
      PYTEST_ADDOPTS: --cov --cov-append -n 5 --color=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          cd Pillar_II/esm/
          pip install -r requirements.txt

      - name: Unit Tests
        timeout-minutes: 3
        run: |
          cd Pillar_II/esm/
          pytest src tests/
